FROM python:3.11-slim

WORKDIR /app

RUN pip install psycopg2-binary

COPY atm_snmp_simulator.py .
COPY ej_log_generator.py .
COPY transaction_feed.py .
COPY grg_snmp_simulator.py .
COPY grg_ej_generator.py .
COPY state_manager.py .
COPY common.py .
COPY sim_engine.py .
COPY txn_engine.py .
COPY ej_engine.py .

CMD ["python3", "ej_log_generator.py"]
